language: php

sudo: false

php:
    - 7.0
    - 7.3
    - 7.4

env:
    - LARAVEL_VERSION=5.4.*
    - LARAVEL_VERSION=5.5.*
    - LARAVEL_VERSION=6.*
    - LARAVEL_VERSION=7.*
    - LARAVEL_VERSION=dev-master

matrix:
    fast_finish: true
    exclude:
        - php: 7.0
          env: LARAVEL_VERSION=5.6.*
        - php: 7.0
          env: LARAVEL_VERSION=5.7.*

        - php: 7.3
          env: LARAVEL_VERSION=5.4.*
        - php: 7.4
          env: LARAVEL_VERSION=5.4.*

before_install:
  - travis_retry composer self-update --stable --no-interaction
  - travis_retry composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update --no-interaction

install:
  - travis_retry composer install --no-suggest --no-interaction

script: vendor/bin/phpunit
