name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.0, 7.2, 7.3, 7.4]
        laravel: [5.4.*, 5.5.*, ^6.0, ^7.0]
        exclude:
          - php: 7.0
            laravel: [^6.0, ^7.0]
          - php: [7.3, 7.4]
            laravel: [5.4.*, 5.5.*]


    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer require "illuminate/contracts=${{ matrix.laravel }}" --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
